title: "Tooba Faisal" # your name (or website title) here
logo: "/images/logo.png?" # your photo (or logo) here
description: Research Web3 Engineer at Nokia Bell-Labs  # your text below (remove <br> elements if you don't need line breaks)

theme: jekyll-theme-minimal


