title: "Tooba Faisal" ###your name (or website title) here
logo: <img src="/images/logo.png?raw=true" width="10" height="10"> # your photo (or logo) here
description: Research Web3 Engineer at Nokia Bell-Labs  # your text below (remove <br> elements if you don't need line breaks)

theme: jekyll-theme-minimal


