title: "Tooba Faisal" #your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: >
PHD scholar at Kings College London  # your text below (remove <br> elements if you don't need line breaks)

theme: jekyll-theme-minimal


